#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OverscanToggle.Resource", IsApplication=true)]

namespace OverscanToggle
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int crop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_crop_black_18dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_crop_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_crop_black_36dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_crop_black_48dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_crop_grey600_18dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_crop_grey600_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_crop_grey600_36dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_crop_grey600_48dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_crop_white_18dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_crop_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_crop_white_36dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_crop_white_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int btn_apply = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int sb_bottom = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int sb_left = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int sb_right = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int sb_top = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int sw_toggle = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int text_bottom = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int text_left = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int text_right = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int text_screenres = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int text_top = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
